# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.find_or_create_by("name" => "Seattle")
Team.find_or_create_by("name" => "Green Bay")
Team.find_or_create_by("name" => "Atlanta")
Team.find_or_create_by("name" => "New Orleans")
Team.find_or_create_by("name" => "Chicago")
Team.find_or_create_by("name" => "Buffalo")
Team.find_or_create_by("name" => "Kansas City")
Team.find_or_create_by("name" => "Tennessee")
Team.find_or_create_by("name" => "St. Louis")
Team.find_or_create_by("name" => "Minnesota")
Team.find_or_create_by("name" => "Miami")
Team.find_or_create_by("name" => "New England")
Team.find_or_create_by("name" => "NY Jets")
Team.find_or_create_by("name" => "Oakland")
Team.find_or_create_by("name" => "Philadelphia")
Team.find_or_create_by("name" => "Jacksonville")
Team.find_or_create_by("name" => "Pittsburgh")
Team.find_or_create_by("name" => "Cleveland")
Team.find_or_create_by("name" => "Baltimore")
Team.find_or_create_by("name" => "Cincinnati")
Team.find_or_create_by("name" => "Houston")
Team.find_or_create_by("name" => "Washington")
Team.find_or_create_by("name" => "Dallas")
Team.find_or_create_by("name" => "San Francisco")
Team.find_or_create_by("name" => "Tampa Bay")
Team.find_or_create_by("name" => "Carolina")
Team.find_or_create_by("name" => "Denver")
Team.find_or_create_by("name" => "Indianapolis")
Team.find_or_create_by("name" => "Detroit")
Team.find_or_create_by("name" => "NY Giants")
Team.find_or_create_by("name" => "Arizona")
Team.find_or_create_by("name" => "San Diego")
