# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.find_or_create_by("name" => "Seattle")
Team.find_or_create_by("name" => "Green Bay")
Team.find_or_create_by("name" => "Atlanta")
Team.find_or_create_by("name" => "New Orleans")
Team.find_or_create_by("name" => "Chicago")
Team.find_or_create_by("name" => "Buffalo")
Team.find_or_create_by("name" => "Kansas City")
Team.find_or_create_by("name" => "Tennessee")
Team.find_or_create_by("name" => "St. Louis")
Team.find_or_create_by("name" => "Minnesota")
Team.find_or_create_by("name" => "Miami")
Team.find_or_create_by("name" => "New England")
Team.find_or_create_by("name" => "NY Jets")
Team.find_or_create_by("name" => "Oakland")
Team.find_or_create_by("name" => "Philadelphia")
Team.find_or_create_by("name" => "Jacksonville")
Team.find_or_create_by("name" => "Pittsburgh")
Team.find_or_create_by("name" => "Cleveland")
Team.find_or_create_by("name" => "Baltimore")
Team.find_or_create_by("name" => "Cincinnati")
Team.find_or_create_by("name" => "Houston")
Team.find_or_create_by("name" => "Washington")
Team.find_or_create_by("name" => "Dallas")
Team.find_or_create_by("name" => "San Francisco")
Team.find_or_create_by("name" => "Tampa Bay")
Team.find_or_create_by("name" => "Carolina")
Team.find_or_create_by("name" => "Denver")
Team.find_or_create_by("name" => "Indianapolis")
Team.find_or_create_by("name" => "Detroit")
Team.find_or_create_by("name" => "NY Giants")
Team.find_or_create_by("name" => "Arizona")
Team.find_or_create_by("name" => "San Diego")


Game.find_or_create_by(game_time: DateTime.parse('20140904 8:30 PM EDT'), home: 'Seattle', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Atlanta', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Chicago', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Kansas City', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'St. Louis', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Miami', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'NY Jets', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Philadelphia', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Pittsburgh', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Baltimore', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20140907 1:00 PM EDT'), home: 'Houston', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20140907 4:25 PM EDT'), home: 'Dallas', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20140907 4:25 PM EDT'), home: 'Tampa Bay', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20140907 8:30 PM EDT'), home: 'Denver', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20140908 7:10 PM EDT'), home: 'Detroit', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20140908 10:20 PM EDT'), home: 'Arizona', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20140911 8:25 PM EDT'), home: 'Baltimore', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Buffalo', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Cincinnati', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Cleveland', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Tennessee', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Minnesota', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'NY Giants', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Washington', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20140914 1:00 PM EDT'), home: 'Carolina', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20140914 4:05 PM EDT'), home: 'San Diego', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20140914 4:05 PM EDT'), home: 'Tampa Bay', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20140914 4:25 PM EDT'), home: 'Denver', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20140914 4:25 PM EDT'), home: 'Green Bay', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20140914 4:25 PM EDT'), home: 'Oakland', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20140914 8:30 PM EDT'), home: 'San Francisco', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20140915 8:30 PM EDT'), home: 'Indianapolis', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20140918 8:25 PM EDT'), home: 'Atlanta', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Buffalo', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Cincinnati', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Cleveland', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Detroit', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'St. Louis', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'New England', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'New Orleans', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'NY Giants', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Philadelphia', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20140921 1:00 PM EDT'), home: 'Jacksonville', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20140921 4:05 PM EDT'), home: 'Arizona', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20140921 4:25 PM EDT'), home: 'Miami', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20140921 4:25 PM EDT'), home: 'Seattle', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20140921 8:30 PM EDT'), home: 'Carolina', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20140922 8:30 PM EDT'), home: 'NY Jets', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20140925 8:25 PM EDT'), home: 'Washington', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Chicago', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Indianapolis', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Oakland', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'NY Jets', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Pittsburgh', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Baltimore', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20140928 1:00 PM EDT'), home: 'Houston', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20140928 4:05 PM EDT'), home: 'San Diego', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20140928 4:25 PM EDT'), home: 'Minnesota', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20140928 4:25 PM EDT'), home: 'San Francisco', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20140928 8:30 PM EDT'), home: 'Dallas', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20140929 8:30 PM EDT'), home: 'Kansas City', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141002 8:25 PM EDT'), home: 'Green Bay', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Dallas', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Detroit', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Tennessee', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Indianapolis', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'New Orleans', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'NY Giants', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Philadelphia', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Carolina', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141005 1:00 PM EDT'), home: 'Jacksonville', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141005 4:05 PM EDT'), home: 'Denver', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141005 4:25 PM EDT'), home: 'San Diego', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141005 4:25 PM EDT'), home: 'San Francisco', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141005 8:30 PM EDT'), home: 'New England', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141006 8:30 PM EDT'), home: 'Washington', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141009 8:25 PM EDT'), home: 'Houston', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Atlanta', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Buffalo', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Cincinnati', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Cleveland', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Tennessee', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Miami', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Minnesota', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'NY Jets', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141012 1:00 PM EDT'), home: 'Tampa Bay', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141012 4:05 PM EDT'), home: 'Oakland', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141012 4:25 PM EDT'), home: 'Arizona', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141012 4:25 PM EDT'), home: 'Seattle', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141012 8:30 PM EDT'), home: 'Philadelphia', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141013 8:30 PM EDT'), home: 'St. Louis', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141016 8:25 PM EDT'), home: 'New England', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Buffalo', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Chicago', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Detroit', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Green Bay', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Indianapolis', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'St. Louis', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Washington', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Jacksonville', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141019 1:00 PM EDT'), home: 'Baltimore', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141019 4:05 PM EDT'), home: 'San Diego', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141019 4:25 PM EDT'), home: 'Dallas', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141019 4:25 PM EDT'), home: 'Oakland', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141019 8:30 PM EDT'), home: 'Denver', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141020 8:30 PM EDT'), home: 'Pittsburgh', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141023 8:25 PM EDT'), home: 'Denver', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141026 9:30 AM EDT'), home: 'Atlanta', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Cincinnati', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Tennessee', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Kansas City', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'New England', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'NY Jets', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Tampa Bay', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Carolina', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141026 1:00 PM EDT'), home: 'Jacksonville', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141026 4:05 PM EDT'), home: 'Arizona', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141026 4:25 PM EDT'), home: 'Cleveland', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141026 4:25 PM EDT'), home: 'Pittsburgh', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141026 8:30 PM EDT'), home: 'New Orleans', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141027 8:30 PM EDT'), home: 'Dallas', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141030 8:25 PM EDT'), home: 'Carolina', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Cincinnati', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Cleveland', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Dallas', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Kansas City', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Miami', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Minnesota', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141102 1:00 PM EST'), home: 'Houston', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141102 4:05 PM EST'), home: 'San Francisco', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141102 4:25 PM EST'), home: 'New England', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141102 4:25 PM EST'), home: 'Seattle', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141102 8:30 PM EST'), home: 'Pittsburgh', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141103 8:30 PM EST'), home: 'NY Giants', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141106 8:25 PM EST'), home: 'Cincinnati', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'Buffalo', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'Detroit', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'New Orleans', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'NY Jets', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'Tampa Bay', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'Jacksonville', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141109 1:00 PM EST'), home: 'Baltimore', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20141109 4:05 PM EST'), home: 'Oakland', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141109 4:25 PM EST'), home: 'Arizona', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141109 4:25 PM EST'), home: 'Seattle', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141109 8:30 PM EST'), home: 'Green Bay', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141110 8:30 PM EST'), home: 'Philadelphia', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141113 8:25 PM EST'), home: 'Miami', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Chicago', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Cleveland', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Green Bay', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Kansas City', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'St. Louis', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'New Orleans', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'NY Giants', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Washington', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141116 1:00 PM EST'), home: 'Carolina', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141116 4:05 PM EST'), home: 'San Diego', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141116 4:25 PM EST'), home: 'Arizona', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141116 8:30 PM EST'), home: 'Indianapolis', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141117 8:30 PM EST'), home: 'Tennessee', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141120 8:25 PM EST'), home: 'Oakland', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Atlanta', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Buffalo', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Chicago', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Indianapolis', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Minnesota', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'New England', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Philadelphia', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20141123 1:00 PM EST'), home: 'Houston', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141123 4:05 PM EST'), home: 'San Diego', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141123 4:05 PM EST'), home: 'Seattle', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141123 4:25 PM EST'), home: 'Denver', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141123 4:25 PM EST'), home: 'San Francisco', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141123 8:30 PM EST'), home: 'NY Giants', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141124 8:30 PM EST'), home: 'New Orleans', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141127 12:30 PM EST'), home: 'Detroit', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141127 4:30 PM EST'), home: 'Dallas', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141127 8:30 PM EST'), home: 'San Francisco', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Buffalo', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Indianapolis', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'St. Louis', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Minnesota', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Pittsburgh', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Tampa Bay', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Jacksonville', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Baltimore', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141130 1:00 PM EST'), home: 'Houston', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20141130 4:05 PM EST'), home: 'Atlanta', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141130 4:25 PM EST'), home: 'Green Bay', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141130 8:30 PM EST'), home: 'Kansas City', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141201 8:30 PM EST'), home: 'NY Jets', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141204 8:25 PM EST'), home: 'Chicago', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Cincinnati', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Cleveland', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Detroit', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Tennessee', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Miami', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Minnesota', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'New Orleans', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Washington', away: 'St. Louis')
Game.find_or_create_by(game_time: DateTime.parse('20141207 1:00 PM EST'), home: 'Jacksonville', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141207 4:05 PM EST'), home: 'Denver', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141207 4:05 PM EST'), home: 'Arizona', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141207 4:25 PM EST'), home: 'Oakland', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141207 4:25 PM EST'), home: 'Philadelphia', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141207 8:30 PM EST'), home: 'San Diego', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141208 8:30 PM EST'), home: 'Green Bay', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141211 8:25 PM EST'), home: 'St. Louis', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Atlanta', away: 'Pittsburgh')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Buffalo', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Cleveland', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Detroit', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Indianapolis', away: 'Houston')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Kansas City', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'New England', away: 'Miami')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'NY Giants', away: 'Washington')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Carolina', away: 'Tampa Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141214 1:00 PM EST'), home: 'Baltimore', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20141214 4:05 PM EST'), home: 'Tennessee', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141214 4:05 PM EST'), home: 'San Diego', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141214 4:25 PM EST'), home: 'Seattle', away: 'San Francisco')
Game.find_or_create_by(game_time: DateTime.parse('20141214 8:30 PM EST'), home: 'Philadelphia', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141215 8:30 PM EST'), home: 'Chicago', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20141218 8:25 PM EST'), home: 'Jacksonville', away: 'Tennessee')
Game.find_or_create_by(game_time: DateTime.parse('20141220 3:33 AM EST'), home: 'Washington', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141220 3:33 AM EST'), home: 'San Francisco', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Chicago', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Miami', away: 'Minnesota')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'New Orleans', away: 'Atlanta')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'NY Jets', away: 'New England')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Pittsburgh', away: 'Kansas City')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Tampa Bay', away: 'Green Bay')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Carolina', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141221 1:00 PM EST'), home: 'Houston', away: 'Baltimore')
Game.find_or_create_by(game_time: DateTime.parse('20141221 4:05 PM EST'), home: 'St. Louis', away: 'NY Giants')
Game.find_or_create_by(game_time: DateTime.parse('20141221 4:25 PM EST'), home: 'Dallas', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141221 4:25 PM EST'), home: 'Oakland', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141221 8:30 PM EST'), home: 'Arizona', away: 'Seattle')
Game.find_or_create_by(game_time: DateTime.parse('20141222 8:30 PM EST'), home: 'Cincinnati', away: 'Denver')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Atlanta', away: 'Carolina')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Green Bay', away: 'Detroit')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Tennessee', away: 'Indianapolis')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Kansas City', away: 'San Diego')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Miami', away: 'NY Jets')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Minnesota', away: 'Chicago')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'New England', away: 'Buffalo')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'NY Giants', away: 'Philadelphia')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Pittsburgh', away: 'Cincinnati')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Tampa Bay', away: 'New Orleans')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Washington', away: 'Dallas')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Baltimore', away: 'Cleveland')
Game.find_or_create_by(game_time: DateTime.parse('20141228 1:00 PM EST'), home: 'Houston', away: 'Jacksonville')
Game.find_or_create_by(game_time: DateTime.parse('20141228 4:25 PM EST'), home: 'Denver', away: 'Oakland')
Game.find_or_create_by(game_time: DateTime.parse('20141228 4:25 PM EST'), home: 'San Francisco', away: 'Arizona')
Game.find_or_create_by(game_time: DateTime.parse('20141228 4:25 PM EST'), home: 'Seattle', away: 'St. Louis')
